### ISSUE TITLE
provider: Only allow code merges if unit test code coverage ratchets up

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/provider#102]
**Is your feature request related to a problem? Please describe.**
We constantly have bug "fixes" where it's just a change to the code, but there are no unit tests. Over time the quality of the sw deteriorates. The excuse is "not enough time" but this is simply untrue because we *do* pay back in spades. Quality comes for free, and then some. So we need to do more tactics to enhance quality. And helping to ratchet up code coverage ratchets up is a good one.

Towards code quality, if we have a constraint where % code coverage must go upwards, it not only prevents code quality from degrading due to missing tests, over time it ratchets the % coverage upwards and therefore quality upwards.

**Describe the solution you'd like**
Only allow a PR to be merged (or a direct commit) if % code coverage doesn't go down.

This is pretty common SW engineering practice. We did it on the bigchaindb code base with good success. Let's do it here.

**Comment by trentmc** [comment]
Suggestion of how to do it:
https://github.com/oceanprotocol/ocean.js/issues/626#issuecomment-784216054

**Comment by kremalicious** [comment]
Same here as [over on ocean.py](https://github.com/oceanprotocol/ocean.py/issues/146#issuecomment-784315423). But this repo does not have any coequality tool setup at all where code coverage reports are sent to. Picking one which support PR status notifications and setting that up is a prerequisite for this issue

**Comment by alexcos20** [comment]
let's setup codeclimate

**Comment by kremalicious** [comment]
there is Codacy setup already and each PR is checked against it,  including coverage as far as I can see, e.g. on https://github.com/oceanprotocol/provider/pull/124

So that sounds like the issue is done?

**Comment by calina-c** [comment]
Done under CodeClimate rules.
