### ISSUE TITLE
Refactor DT Order handling (provider)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#112]
see [Refactor DT Order handling Epic)(https://github.com/oceanprotocol/multi-repo-issue/issues/85) for details

**Comment by alexcos20** [comment]
ignore it please

**Comment by alexcos20** [comment]
Fix for the moment with https://github.com/oceanprotocol/privateissues/issues/8

**Comment by calina-c** [comment]
@alexcos20 @AnaLoznianu I think this can be closed?
