### ISSUE TITLE
Provider fails to start

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#114]
**Describe the bug**
In barge, sometimes provider fails to start, breaking all testing for both ocean.js/py.

**To Reproduce**
https://travis-ci.com/github/oceanprotocol/ocean.js/builds/219392001#L761
https://travis-ci.com/github/oceanprotocol/ocean.py/builds/219298678#L674

Check out travis builds

**Expected behavior**
Provider should start without errors

**Comment by ssallam** [comment]
This appears to be fixed by the changes in #115.
