### ISSUE TITLE
Compute service fails

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/provider#119]
When trying to start a compute job from market the /services/compute post method returns a 500 error: "Error : MAC check failed"
Mentioned api is called from oceanJS , compute start method https://github.com/oceanprotocol/ocean.js/blob/main/src/ocean/Compute.ts#L128
the payload sent was the following:
{
algorithmDataToken: "0x9fF1677B39beFAb709fe449dCDA1e0fC36fEc438"
algorithmDid: "did:op:9fF1677B39beFAb709fe449dCDA1e0fC36fEc438"
algorithmTransferTxId: "0x5fd819bf4423452098ea60187d01889023870bb71cf6a505d8db10c73c6a4ee9"
consumerAddress: "0x968d4670c346275edd5CC1A7535D14b631FFc49C"
dataToken: "0x8A8DbFbC8e562f6A31A031f364F419d2AF0f438F"
documentId: "did:op:8A8DbFbC8e562f6A31A031f364F419d2AF0f438F"
output: {publishAlgorithmLog: false, publishOutput: false}
serviceId: "1"
serviceType: "compute"
signature: "0x84d0c489f5f7e76e7c29bc116ea8740639af508e979d8ffc3a4cb774731350242cd1a0b00d7c6dfac9c1f2e6bb196b6b7e1066ba039a1cf1f1b6c897e366b5061b"
transferTxId: "0x83482f90abb8c14c0dc1e07d0f285f6185bfc31f19af06bc5392cb6dfac82f96"
}

1. Go to https://market-fm37mlldc-oceanprotocol.vercel.app/
2. Navigate to a compute asset of your choice
3. Select and algorithm 
4.  Open console
5. Click star compute
6.  See error

![Screenshot 2021-03-22 at 15 56 29](https://user-images.githubusercontent.com/13447142/112516856-61cc6100-8da0-11eb-963e-225d493064ad.png)

 - OS: [e.g. MacOS]
 - Browser [e.g. Chrome,]
 - Version [e.g. 89]

**Comment by calina-c** [comment]
@alexcos20 Is this is related to the checksum fixes we did Friday?

**Comment by bogdanfazakas** [comment]
Yeah it was fixed we can close this I guess, there were 2 issue behind, an older version of provider on rikeby and the issue related to the checksum.
