### ISSUE TITLE
Add dids in compute job

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#126]
When fetching the status of compute jobs `api/v1/services/computedocumentId=&consumerAddress=0x4D156A2ef69ffdDC55838176C6712C90f60a2285` we need the array of dids of the job
```
agreementId: "c228efe163904970ab621b26297dd38a7cee7a60f15b47eca413b3f50cfd3738"
dateCreated: 1585659529.90721
dateFinished: 1585659660.71269
jobId: "94fd89fa9d4843b6bbd8ea588986767f"
removed: 0
status: 70
statusText: "Job finished"
stopreq: 0
dids: ["did1","did2"]
```
Doesn't have to be called `dids` it was just a quick example in lack of a better name.

**Comment by alexcos20** [comment]
done in op-service, it's called "input"
