### ISSUE TITLE
Fileinfo inaccuracies 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#158]
A post to https://provider.rinkeby.oceanprotocol.com/api/v1/services/fileinfo

with 
```
{
    "did":"did:op:bB0cd268D08A632c4da479f25a7D3AcAEDd8224b"
}
```
returns 
```
[
    {
        "index": 0,
        "valid": true,
        "contentLength": "",
        "contentType": "text/html; charset=utf-8"
    }
]
```

with 
```
{
    "url":"https://raw.githubusercontent.com/oceanprotocol/ocean.js/main/src/data/words.json"
}
```
returns
```
[
    {
        "index": 0,
        "valid": true,
        "contentLength": "1084",
        "contentType": "text/plain; charset=utf-8"
    }
]
```

I published the did and i used this file url.

**Comment by calina-c** [comment]
@mihaisc I published the same asset on a local ganache. I got the correct result for the fileInfo call.
Does this happen on every request?

**Comment by mihaisc** [comment]
All the time

**Comment by calina-c** [comment]
discussed with @mihaisc: there seems to be an inconsistency with the URL used before encryption. It seems to be 

https://github.com:443/oceanprotocol/ocean.js/blob/main/src/data/words.json

AND NOT

https://raw.githubusercontent.com/oceanprotocol/ocean.js/main/src/data/words.json

Mihai will look for more examples.
