### ISSUE TITLE
Improve fileInfo url check

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#161]
Currently we check options and the get. We should check head first. HEAD > OPTIONS > GET

Another suggestion (not sure how good it is, we need to test) is to go to the next method if the current one returns content length 0

**Comment by kremalicious** [comment]
And there would be more. We should simply replicate whatever our old fileinfo app did, as that was (and still is) working flawlessly. E.g. the `content-range` seems to be missing too https://github.com/oceanprotocol/fileinfo/blob/main/api/index.ts#L22-L23

**Comment by kremalicious** [comment]
Also, does it support passing an IPFS content hash as the old fileinfo app did?

**Comment by calina-c** [comment]
> Also, does it support passing an IPFS content hash as the old fileinfo app did?

Yes, and there's a test for it:

<img width="469" alt="Screenshot 2021-06-23 at 11 02 10" src="https://user-images.githubusercontent.com/4101015/123059449-76a5a880-d412-11eb-8b7e-41dd8ed2357f.png">

(I assume this is what you mean)
