### ISSUE TITLE
Failed consuming asset that have values on allow/deny list

### ISSUE THREAD

**Issue by dungeonhao** [oceanprotocol/provider#193]
**Describe the bug**
Failed to consuming asset that have values on allow/deny list. The error happened on provider, it will return 503 error. Even when your wallet are on allow-list / not on deny-list. 

![image](https://user-images.githubusercontent.com/34234250/127624356-af00da5b-4a41-445f-9687-9fe4ca1e6ed6.png)

**To Reproduce**
1. Go to https://market.oceanprotocol.com/asset/did:op:9136b665f7E76674C8f3492361363cb394BB5DA1 (Or any asset that have allow/deny list in the DDO) 
2. Consume the asset

Suspected this happened because of ocean.py. 
https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/common/ddo/credentials.py#L12-L17

Here's a sample provider error log 
```
2021-07-30 05:07:17,546 - ocean_provider.routes.consume - ERROR - Payload was: documentId=did:op:504E3D6D23aE92a412969C0F167bAa7399E48954,serviceId=1,serviceType=access,dataToken=0x504E3D6D23aE92a412969C0F167bAa7399E48954,consumerAddress=0x9bf750b5465a51689fa4235aac1f37ec692ef7b4
Traceback (most recent call last):
  File "/ocean-provider/ocean_provider/routes/consume.py", line 230, in initialize
    consumable, message = check_asset_consumable(asset, consumer_address, logger)
  File "/ocean-provider/ocean_provider/utils/util.py", line 347, in check_asset_consumable
    code = asset.is_consumable(
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/common/ddo/ddo.py", line 456, in is_consumable
    if manager.requires_credential():
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/common/ddo/credentials.py", line 22, in requires_credential
    denied_addresses = self.get_addresses_of_class("deny")
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/common/ddo/credentials.py", line 16, in get_addresses_of_class
    [addr.lower() for addr in address_entry["values"]] if address_entry else []
KeyError: 'values'
```

**Comment by mariacarmina** [comment]
**Payload**
`{
  "@context": "https://w3id.org/did/v1",
  "id": "did:op:B165A080e666808212b9F5d06a3dB5e456fa9C7D",
  "created": "2021-07-20T06:18:43Z",
  "updated": "2021-08-02T01:07:37Z",
  "dataToken": "0xB165A080e666808212b9F5d06a3dB5e456fa9C7D",
  "publicKey": [
    {
      "id": "did:op:B165A080e666808212b9F5d06a3dB5e456fa9C7D",
      "type": "EthereumECDSAKey",
      "owner": "0x9Bf750b5465a51689fA4235aAc1F37EC692ef7b4"
    }
  ],
  "authentication": [
    {
      "type": "RsaSignatureAuthentication2018",
      "publicKey": "did:op:B165A080e666808212b9F5d06a3dB5e456fa9C7D"
    }
  ],
  "service": [
    {
      "type": "metadata",
      "attributes": {
        "status": {
          "isListed": true,
          "isRetired": false,
          "isOrderDisabled": true
        },
        "main": {
          "type": "dataset",
          "name": "Test rinkeby rbac aqua 3",
          "dateCreated": "2021-07-20T06:17:46Z",
          "author": "ZH",
          "license": "https://market.oceanprotocol.com/terms",
          "files": [
            {
              "contentLength": "981",
              "contentType": "application/json",
              "index": 0
            }
          ],
          "datePublished": "2021-08-02T01:07:46Z"
        },
        "additionalInformation": {
          "description": "Test rinkeby rbac aqua 3 a",
          "tags": [
            ""
          ],
          "termsAndConditions": false,
          "source": "ddmdev",
          "isExperiemental": false,
          "links": []
        },
        "encryptedFiles": "0x046dba8c30b1b5f1e4261eb042950ea89ce5f056e69f2228df978fd50cd459fac2454f322da0b607dc77dbb256324ba884660d61f226d2b6303fa958fefef5284e6a9136d8f70715e7d5fbcb6ef17b437be729cb340f563e69e8c849e4ad82ba0ade3fc5cd92cffdce41689cd54860b22249966303843c46cee527fae02c28b1ac8796f0fd93ee457b7bc6f6f7896b90024e2bb0c88e92ccf0e3106ca793f0d6bbccc5c0ee4f4dcb51a919b85fbd73d71c34903c135a9006a8d770151b7f57524c9e4272edb207f670ced8b5",
        "curation": {
          "rating": 0,
          "numVotes": 0,
          "isListed": true
        }
      },
      "index": 0
    },
    {
      "type": "access",
      "index": 1,
      "serviceEndpoint": "https://provider.rinkeby.dev.acentrik.io",
      "attributes": {
        "main": {
          "creator": "0x9Bf750b5465a51689fA4235aAc1F37EC692ef7b4",
          "datePublished": "2021-07-20T06:17:46Z",
          "cost": "1",
          "timeout": 0,
          "name": "dataAssetAccess"
        }
      }
    }
  ],
  "proof": {
    "created": "2021-07-20T06:18:29Z",
    "creator": "0x9Bf750b5465a51689fA4235aAc1F37EC692ef7b4",
    "type": "AddressHash",
    "signatureValue": "0x5bfc7bb128d6a0e6cf7c9bdc9d7c60f44bc6de83a1f501cc1530729b9a82f3f8"
  },
  "isInPurgatory": "false",
  "dataTokenInfo": {
    "address": "0xB165A080e666808212b9F5d06a3dB5e456fa9C7D",
    "name": "Exceptional Herring Token",
    "symbol": "EXCHER-38",
    "decimals": 18,
    "cap": 1000
  },
  "credentials": {
    "allow": [
      {
        "type": "address",
        "value": [
          "0x9bf750b5465a51689fa4235aac1f37ec692ef7b4",
          "0xe25dc777a144436d00f4972dc78364125d08411e"
        ]
      }
    ],
    "deny": [
      {
        "type": "address",
        "value": [
          "0xe25dc777a144436d00f4972dc78364125d08411d",
          "0xe25dc777a144436d00f4972dc78364125d084111",
          "0xe25dc777a144436d00f4972dc78364125d084112",
          "0xe25dc777a144436d00f4972dc78364125d084113",
          "0xe25dc777a144436d00f4972dc78364125d084114",
          "0xe25dc777a144436d00f4972dc78364125d084115",
          "0xe25dc777a144436d00f4972dc78364125d084116",
          "0xe25dc777a144436d00f4972dc78364125d084117",
          "0xe25dc777a144436d00f4972dc78364125d084118",
          "0xe25dc777a144436d00f4972dc78364125d084119",
          "0xe25dc777a144436d00f4972dc78364125d084121"
        ]
      }
    ]
  },
  "chainId": 4,
  "accessWhiteList": [],
  "event": {
    "txid": "0x8e243b4d10b8ee7108446c286edfa24bf818051be5ea7cad32d8fdcea35efb4e",
    "blockNo": 9041809,
    "from": "0x9Bf750b5465a51689fA4235aAc1F37EC692ef7b4",
    "contract": "0xFD8a7b6297153397B7eb4356C47dbd381d58bFF4",
    "update": true
  }
}`
**Possible problem**
In our samples of ddo credentials, in _allow_ and _deny_ lists, we have _values_ as key, not _value_.

**Comment by alexcos20** [comment]
yes, it should be values, according to the OEP: https://github.com/oceanprotocol/OEPs/tree/master/7/v0.3#credentials

**Comment by mariacarmina** [comment]
It was a confusion due to the fact that ocean.js uses `value` instead of `values` https://github.com/oceanprotocol/ocean.js/blob/e40c5f0c34ec3fa0f07e395b24564bb5d103baf5/src/ddo/interfaces/Credentials.ts#L8-L11. We can create a PR for ocean.js where we can modify so that the keys match.

**Comment by alexcos20** [comment]
But anyway, provider should check for that key and return a nice error, rather then assert

**Comment by mariacarmina** [comment]
Agreed.

**Comment by alexcos20** [comment]
fixed in ocean.py, needs a new release & provider bump
