### ISSUE TITLE
Rinkeby Provider not working with market

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/provider#202]
I noticed something weird while testing the market on Rinkeby. After successfully publishing a dataset it says there is "no file info available" for the dataset and when I try to purchase it, I get the error message saying the URL is unavailable.
I was using a simple [url to a csv](https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv) in the test which seems to work fine, and the provider confirmed it was valid while publishing.

![no file data](https://user-images.githubusercontent.com/20739535/130277984-8b24568c-722e-4646-a114-ebc97bc21a55.png)

I have done two tests and the same things happened both times ([1](https://market.oceanprotocol.com/asset/did:op:e5aaA6800e8ea532d106DbcBFdAeb62bfe4aF55D) and [2](https://market.oceanprotocol.com/asset/did:op:5Ce833BA3Bf48421d6B54c9CF688AfEB4DB7A409))

**Comment by md00ux** [comment]
changed **AQUARIUS_URL** to https://aquarius.oceanprotocol.com

**Comment by kremalicious** [comment]
great thanks, this was it. Can see fileinfo now on all mentioned Rinkeby assets. Maybe let's double check that all other providers have the same `AQUARIUS_URL`?

**Comment by md00ux** [comment]
already changed for:
- mainnet
- ropsten
- polygon
- bsc

**Comment by kremalicious** [comment]
awesome, thanks. Then I think this is all solved now

![giphy-2](https://user-images.githubusercontent.com/90316/130452691-4b8ffae6-476b-45df-8491-2a4e347cfa94.gif)

**Comment by jamiehewitt15** [comment]
Yeah seems to be working now
