### ISSUE TITLE
Add `/fileinfo` endpoint input args `serviceId` 

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/provider#243]

**Comment by DMats** [comment]
In the v4 DDO structure, `files` is moved inside `services`, so when querying `/fileinfo` endpoint, it needs to know which service. `/fileinfo` endpoint should allow caller to send `serviceId` or `serviceIndex` to specify service.

**Comment by calina-c** [comment]
Closed by https://github.com/oceanprotocol/provider/pull/258
