### ISSUE TITLE
Update unit tests to expect chain id 8996 instead of 1337

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/provider#246]
The barge ganache chain ID should be 8996.  This issue is to update any places where chain_id of ganache is hardcoded to 1337.

**Comment by DMats** [comment]
@AnaLoznianu I saw you scheduled this for the next sprint, but I believe it is blocking many of the provider unit tests, particularly the `download` ones that I want to work on, so I to moved it to in progress and assigned myself.

**Comment by AnaLoznianu** [comment]
@DMats Feel free to take whatever is blocking current deliverables
