### ISSUE TITLE
Check Provider behaviour with large files  (several GB)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#253]
**Describe the bug**
Got some reports that provider fails with large files.
  - requests fails
  - download data is smaller then expected (600Mb instead of 1 Gb, next try 700Mb from the same 1Gb file)
We need some tests

**Comment by AnaLoznianu** [comment]
@alexcos20 I moved this to the V4 milestone and closed the V3 freeze milestone
