### ISSUE TITLE
Retry mechanism on establishing connection with actual data/asset hosting

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/provider#254]
### Describe the bug
Sometime during certain **split second**, provider couldn't establish connection to actual data/asset hosting. Result to fail download respond/ and sometime opening a new black page with some json error below:
`{"error": "HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=3)", "context": {"documentId": null, "consumerAddress": "0x2E33C6014222A47585605F8379a1877eaaF0ec13", "serviceId": "1", "serviceType": "access"}}`

### Potential solution
Maybe we could add a N number of retry mechanism to avoid such problem.
Potentially apply on: https://github.com/oceanprotocol/provider/blob/f5d926eeda05bb9cdd349ded6e08d8685916fd28/ocean_provider/utils/url.py#L120

**Comment by alexcos20** [comment]
after this is done, we should replicate it to v4 as well
