### ISSUE TITLE
Send provider wallet address in RBAC requests

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/provider#255]
This issue is related to the following task: https://github.com/oceanprotocol/RBAC-Server/issues/43 

The new request format needs to include `"providerAddress": "0x123"` when the `eventType` is publish. It is not necessary when the `eventType` is consume. This is so that we can check if the user is allowed to publish with that specific provider. 

```
{
    "component": "market",
    "eventType": "publish",
    "providerAddress": "0x123",
    "credentials": {
        "type": "address",
        "value": "0xA78deb2Fa79463945C247991075E2a0e98Ba7A09"
    }
}
```

**Comment by mariacarmina** [comment]
The `providerAddress` is already set in all the requests. I will add some assertions for this field to make sure that it is included in all the requests.

**Comment by jamiehewitt15** [comment]
Thank you @mariacarmina
