### ISSUE TITLE
Nonce improvment (v4)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#270]
Right now, provider is using a fixed nonce (meaning all requests must have a nonce = provider_stored_nonce)
This is cumbersome, what endpoint are incrementing that and what endpoints do not ?
An additional enpoint call is needed, in order to get the nonce from provider, increasing bandwith usage & using provider workers

Solution:
 - make nonce a float , so we can use timestamps with microseconds
 - all calls requiring a nonce should check if the incoming nonce  (specified in the request) is higher (and not equal to) then provider_stored_nonce.  If yes, request is valid and provider_stored_nonce = new_received_nonce
 - all clients (ocean.js/.py, market) can use timestamp (with microseconds) as nonce, thus not worrying about getting the last nonce
 - keep getNonce endpoint, if client wants to build custom nonce tracking

Con:
 - an address cannot have more then one call per microsecond, but we can live with that

**Comment by calina-c** [comment]
Closed by #279
