### ISSUE TITLE
Expose asset URL(s) (V4)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#282]
Right now, the asset url(s) are stored encrypted.
But what if you want to : 
 - add a new url
 - change a provider for a specific service
Then, you need the plain url.  Of course, we need to make sure that only NFT Owner has rights to access this endpoint.

Q: Do we need to add additional roles? Should metadataupdater be allowed as well ?

Input required:  did, serviceId , nonce , signature
Output:  json object

**Comment by calina-c** [comment]
Done and merged with #289.
