### ISSUE TITLE
Support 'url' type of storage

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#283]
According to https://github.com/oceanprotocol/docs/pull/837 , the provider will support different types of storage.
It will affect download, file info, initialize, compute, etc

[
   {
      "type": "url",
      "url": "https://url.com/file1.csv",
      "method": "GET"
   }
]

Docs: https://deploy-preview-837--docs-oceanprotocol.netlify.app/concepts/did-ddo/

**Comment by DMats** [comment]
Since #294 is merged, I am closing this issue.
