### ISSUE TITLE
Upgrade web3.py to latest stable version, continue using legacy transactions

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/provider#284]
EDIT:
Upgrading to use EIP-1559 transactions is blocked by oceanprotocol/barge#277.

So we have decided to reduce the scope of this issue to simply update to the latest stable Web3.py but continue using legacy transactions.

- [ ] v3 (`main` branch)
- [ ] v4 (`v4main` branch)

**Comment by DMats** [comment]
Upgrading to use EIP-1559 transactions is blocked by https://github.com/oceanprotocol/barge/issues/277.

So we have decided to reduce the scope of this issue to simply update to the latest stable Web3.py but continue using legacy transactions.
