### ISSUE TITLE
Prevent leaking URLs via error responses

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/provider#290]
This issue is to cherry-pick PR #288 (https://github.com/oceanprotocol/provider/commit/df9bd6d215558dfd9a2d72cbe4f58d279814a37f) into `v4main` branch.

**Comment by DMats** [comment]
@alexcos20 requested I change the design to strip out all URLs, rather than stripping only Infura-specific endpoint URLs.

**Comment by alexcos20** [comment]
superseded by #292
