### ISSUE TITLE
Document all ENV vars

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#300]
We should have a section in the README documenting all ENV variables

**Comment by calina-c** [comment]
The entire provider docs need work on. Should I or @akshay-ap take this? CC: @alexcos20 @AnaLoznianu

**Comment by akshay-ap** [comment]
I can take this. Is that fine?

**Comment by AnaLoznianu** [comment]
@akshay-ap Yes please

**Comment by calina-c** [comment]
Closed with the addition of https://github.com/oceanprotocol/provider/blob/v4main/README.md#environment-variables.
