### ISSUE TITLE
File info endpoint

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#32]
Since the provider should be the only component that can access a dataset URL, we need to implement a fileinfo endpoint,

GET /api/v1/services/fileinfo?url=XXX

For a given URL, it should return a json response containing at least contentLength and contentType

 ResponseResult = {
    contentLength,
    contentType
  }

**Comment by calina-c** [comment]
Duplicated by #42. Sorry, I didn't see this one.
