### ISSUE TITLE
The Provider config should have the option to be set as public/private

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/provider#324]
A recent upgrade to the RBAC server has now set up a check to find if a user is allowed to use the particular provider. We can improve this process by setting an env within the provider that can be set as `public` or `private` - that way the check can be skipped when the provider is public (e.g. all users are automatically allowed to use it). This would simplify the process and avoid an unnecessary API call.

**Comment by soonhuat** [comment]
As of now, there is 2 type of checking apply to provider:
1. previous RBAC (role based access right and allow/deny within ddo): this would affect asset and event access
2. extended RBAC check for private provider (implemented recently): this will only allow specific wallet to access private provider by event

for the public provider, it should only skip the checking on 2.

**Comment by jamiehewitt15** [comment]
So we can update the request that is sent to the RBAC server so that the `providerAccess` (public/private) is included. For example: 

```
{ 
     "eventType": "consume", 
     "component": "market" ,
     "did": "did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38",
     "providerAddress": "0xf31FC0D18A24c6Ae4225A0d4eEB709AC0a18E993",
     "providerAccess": "public",
     "credentials": {
              "type": "address",
              "value": "0xB149C36986cf8e2B260d2Eb02AFf97058a1a5C95"
     }
}
```
