### ISSUE TITLE
Provider checks publisher DT balance after order

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#331]
In provider he have the following code:

https://github.com/oceanprotocol/provider/blob/v4main/ocean_provider/utils/datatoken.py#L173-L186

I wonder how this was tested with : 
https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/templates/ERC20TemplateEnterprise.sol#L496-L497

**Comment by AnaLoznianu** [comment]
- [ ] Remove the check
- [ ] Add a check that the ERC20 token is derived from the ERC721 token
- [ ] Add ERC20Enterprise tests
