### ISSUE TITLE
Wrong & innocuous parameter fetching from POST payload in compute endpoint

### ISSUE THREAD

**Issue by md0x** [oceanprotocol/provider#357]
Some parameters in compute post endpoint are not obtained correctly from the payload, resulting in None values. 

Since the tests are still passing, we should check if these values can be removed or need to be corrected.

```
tx_id = data.get("transferTxId") # should be data.get("dataset").get("transferTxId")
did = data.get("documentId") # should be data.get("dataset").get("documentId")
```

This is the payload:
```
{
            "dataset.documentId": ["bail", "required"],
            "dataset.serviceId": ["bail", "required"],
            "dataset.transferTxId": ["required"],
            "algorithm.documentId": [
                "required_without:algorithm.meta",
                "required_with_all:algorithm.serviceId,algorithm.transferTxId",
            ],
            "algorithm.meta": ["required_without:algorithm.documentId"],
            "consumerAddress": ["bail", "required"],
            "nonce": ["bail", "required", "numeric"],
            "signature": [
                "bail",
                "required",
                "signature:consumerAddress,dataset.documentId,jobId,nonce",
            ],
        }
```

https://github.com/oceanprotocol/provider/blob/9e222ab2c88bfc7b90e6b08b3c55a279fd942247/ocean_provider/routes/compute.py#L286
https://github.com/oceanprotocol/provider/blob/9e222ab2c88bfc7b90e6b08b3c55a279fd942247/ocean_provider/routes/compute.py#L285

**Comment by calina-c** [comment]
Please check what c2d expects there and remove or correct the agreementId and documentId parameters from the generated payload.
