### ISSUE TITLE
Endpoint expose

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#36]
On the root endpoint, each provider should expose a json that looks like:

{
   "network-url":"mainnet",
   "provider-address":"0xeAFDC69612a8bF720FBfE6A5520Cfede69a9a5b5",
   "software":"Provider",
   "version":"0.4.0",
   "serviceEndpoints":{
      "download": ("GET", "/api/v1/services/download"),
      "computeStart": ("POST", "/api/v1/services/compute"),
      "computeDelete": ("DELETE", "/api/v1/services/compute"),
      "computeStop": ("PUT", "/api/v1/services/compute"),
      "computeStatus": ("GET", "/api/v1/services/compute"),
      "nonce": ("GET", "/api/v1/services/nonce"),
      "encrypt": ("POST", "/api/v1/services/encrypt"),
      "initialize": ("GET", "/api/v1/services/initialize"),
   }
}

this will allow dynamic services types

The provider already has the root endpoint. This task adds the `serviceEndpoints` dict to that.

* Include all the provider service endpoints (preferrably using a dynamic approach)
* Include the HTTP method along with the endpoint url
* Remove/delete the simple flow endpoint (`simple_flow_consume`)

**Comment by mariacarmina** [comment]
I think computeDelete should have a DELETE method instead of GET and also computeStatus should have GET instead of DELETE. Maybe you have just switched them.

**Comment by ssallam** [comment]
> I think computeDelete should have a DELETE method instead of GET and also computeStatus should have GET instead of DELETE. Maybe you have just switched them.

yes, i think I made some mistakes, i'll make correction to the description
