### ISSUE TITLE
Provider fails to boot if there is no OPERATOR_URL defined

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#394]
<img width="1154" alt="Screenshot 2022-03-14 at 16 19 03" src="https://user-images.githubusercontent.com/7489447/158193558-057a484e-552a-4154-82d1-d1f5b53e57a3.png">

Fixes:

- [ ] V3
- [ ] V4

If OPERATOR_URL is not defined, then provider should not expose any C2D endpoints

**Comment by air3ijai** [comment]
Hello,

This issue was fixed only for v4. What is about v3, will it receive fixes from the latest version?
