### ISSUE TITLE
`decrypterAddress` ambiguous argument name

### ISSUE THREAD

**Issue by MantisClone** [oceanprotocol/provider#434]
The `decrypterAddress` argument of the `decrypt` endpoint is an ambiguous name. I wish I had instead named it `decryptRequesterAddress` sweat_smile But changing it at this point would have a ripple effect through other components. This issue is created to make note of the ambiguity with the recognition that fixing it is likely a very low priority.

**Comment by AnaLoznianu** [comment]
A minor issue that involves a lot of changes in the entire stack. Not doing it
