### ISSUE TITLE
Make 400 error responses more descriptive

### ISSUE THREAD

**Issue by MantisClone** [oceanprotocol/provider#448]
**Is your feature request related to a problem? Please describe.**
The 400 error responses returned by provider endpoints aren't as descriptive as they could be.  

1. Error responses are not returned promptly and instead fall through, waiting until later code blocks fail.
2. A try/catch masks the underlying exception by not including the underlying Exception string in the error response.  
3. Failures are silently ignored by returning `None` or `[]` instead of throwing an Exception. 
4. Error responses say what happened, but don't include enough detail for the user to know how to fix it.

**Describe the solution you'd like**
Go through each provider endpoint and improve error messages and error handling logic. Error responses should be returned promptly after errors occur (not waiting for later stages of logic to catch them). Error responses should be descriptive and not lump together multiple error cases.  If a given line can fail due to several causes then there should be a separate error_response for each failure case. If an error is caused by an exception deeper in the code, then that exception string should be returned as part of the error response.

**Comment by DMats** [comment]
Here's an example where the download endpoint requests a cached asset from Aquarius by calling `get_asset_from_metadatastore()`. 

If the Aquarius endpoint is non-responsive OR if the response code is not `200`, indicating success, then `get_asset_from_metadatastore` returns `None` and the download endpoint continues processing.

Instead, what it should do is immediately return an error response to the caller indicating what went wrong.

https://github.com/oceanprotocol/provider/blob/c7f6b8cc3c1d17b00c4b7158aab60944d92ff0c4/ocean_provider/routes/consume.py#L240-L243

I personally think `get_asset_from_metadatastore` should throw an Exception if the Aquarius endpoint doesn't return a successful response. And then that exception should be caught inside `download` and an error response should be sent back to the caller.

**Comment by DMats** [comment]
Here's another example where the `get_c2d_environments` returns an empty list `[]` if the `OPERATOR_SERVICE_URL` envvar is not set.

https://github.com/oceanprotocol/provider/blob/c7f6b8cc3c1d17b00c4b7158aab60944d92ff0c4/ocean_provider/routes/consume.py#L245-L246

In this case, it should instead throw an Exception indicating that it needs this envvar.

It should throw a different exception if the response from the c2d backend is not successful.

All of these exceptions should be caught inside `download` and an error response returned to the caller indicating what went wrong.

**Comment by AnaLoznianu** [comment]
Return specific error codes for the 400 errors
