### ISSUE TITLE
http range

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#488]
**Is your feature request related to a problem? Please describe.**
Sometime, a client will only need parts of a file.

Imagine a youtube built on top of ocean.   The player will requests only chunk of bytes (cache, seek, etc) and not the entire content (maybe TB of data).

**Describe the solution you'd like**
Provider should obey all Range Requests headers (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#range_requests)  which are passed in the request headers

**Comment by calina-c** [comment]
Possibly to be closed by https://github.com/oceanprotocol/provider/pull/507

**Comment by calina-c** [comment]
Closed by #507.
