### ISSUE TITLE
auth token

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#489]
For every download (and other actions), you need to sign your request.
But what if we have something that needs a lot of requests (MediaPlayers) or some kind of automation?
Or for better UX, maybe our market can generate one day valid token for a user

Proposal:
 - add new endpoint createToken, which accepts a signed requests and a validUntil parameter and creates an auth-token 
 - add new endpoint deleteToken, which accepts a signed requests and a auth-token and invalidates an already existing auth-token 
 - auth-token can be used wherever signing is required, as long as it's still valid

Additional requirements:
 - if signature is present in params, it has priority vs auth-token
 - nonce is always mandatory.
 - auth-token internally maps to a address, so all internal auth/nonce functions are going to use that address

Pass it in a http header like Authorization

**Comment by AnaLoznianu** [comment]
We need a Redis DB to store auth tokens.
