### ISSUE TITLE
Storage type "URL" should support headers

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#492]
**Is your feature request related to a problem? Please describe.**
Sometimes, an asset can have files that are protected using some bearer tokens or api keys, which are stored as headers.
A publisher could have this definition for an asset:
```
[
    "type": "url",
    "url": "https://url.com/file1.csv",
    "method": "GET",
    "headers":
      [
       {"Authorization": "Bearer 123"}, 
       {"APIKEY": "124"},
      ]
```
In the current setup, download will fail, because APIKEY header is not sent

Since in https://github.com/oceanprotocol/docs/pull/1029 we added the headers object, Provider should add (if existing) asset defined headers to the request when downloading

**Comment by soonhuat** [comment]
@alexcos20 perhaps also enhance fileinfo endpoint to append the headers to do the ping check and checksum.
by both did (asset detail page) and url (during publish flow)
