### ISSUE TITLE
Provider fee validity check (initializeCompute) will forever expired

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/provider#503]
**Description**
Provider initializeCompute endpoint will receive request body compute.validUntil which is calculated market at the moment user selected algorithm, validity check will forever return false because the validUntil will always greater than previous purchased provider fee validUntil.
https://github.com/oceanprotocol/provider/blob/15e7c52f63644e0441c9e35785730c8a6a6a8dba/ocean_provider/utils/provider_fees.py#L134

Scenario:
1. User A selected algorithm, thus, compute.validUntil calculated as (current timestamp 10000 + 15min of c2d env 900) = 10900
2. User A ordered both dataset and algorithm, and started a compute job
3. 20 second later (assume the compute job ran completed), User A want to re-trigger compute,  so now after selecting same algorithm, compute.validUntil will calculate again (current timestamp 10020 + 15min of c2d env 900) = 10920
4. initializeCompute respond will return **both validOrder** and **providerFee object** because 10920 > 10900, although current timestamp is just 10020 which suppose to be still valid (provider fee valid until 10900)

at step 4, below line does the checking which will forever return false even 1 millisecond passed.
https://github.com/oceanprotocol/provider/blob/15e7c52f63644e0441c9e35785730c8a6a6a8dba/ocean_provider/utils/provider_fees.py#L134

OceanJs test case success because the same value of computeValidUntil is defined and been re-used in multiple test scenario (just like time frozen), thus, when initializeCompute, the checking won't face the above scenario
https://github.com/oceanprotocol/ocean.js/blob/7772e9387ef9d63f98ea80cfd4eefbea963dd0ad/test/integration/ComputeFlow.test.ts#L56

**Describe the solution**
Not sure how we could predict or estimate the compute job duration, perhaps 
`if timestamp <= log_valid_until`
is good enough?

**Comment by alexcos20** [comment]
Since provider validUntil is an absolute time, there are 2 scenarios:
 - a new initializeCompute, with validUntil <= previous validUntil -> will return validOrders
 - a new initializeCompute, with validUntil > previous validUntil -> will return validOrders and new providerFees

So this is not a bug.

**Comment by soonhuat** [comment]
Common use case such as below:
1. User A selected algorithm, thus, compute.validUntil calculated as (current timestamp 10000 + 15min of c2d env 900) = 10900
2. User A ordered both dataset and algorithm, and started a compute job
3. 20 second later (assume the compute job ran completed), User A want to re-trigger compute, so now after selecting same algorithm, compute.validUntil will calculate again (current timestamp 10020 + 15min of c2d env 900) = 10920
4. initializeCompute respond will return both validOrder and providerFee object because 10920 > 10900, although current timestamp is just 10020 which suppose to be still valid (provider fee valid until 10900)

OR

1. User B selected algorithm, thus, compute.validUntil calculated as (current timestamp 10000 + 15min of c2d env 900) = 10900
2. User B ordered both dataset and algorithm, and started a compute job
3. User B refresh the page after 20 second, then initializeCompute kick in which  re-trigger compute, so now after selecting same algorithm, compute.validUntil will calculate again (current timestamp 10020 + 15min of c2d env 900) = 10920
4. initializeCompute respond will return both validOrder and providerFee object because 10920 > 10900, although current timestamp is just 10020 which suppose to be still valid (provider fee valid until 10900)

there will be only scenario which is _new initializeCompute, with **validUntil > previous validUntil** -> will return validOrders and new providerFees_

the only scenario of **validUntil  <= previous validUntil** happen is:
1. Ninja user initiate 2nd compute job without trigger initializeCompute
2. via SDK without request initializeCompute
3. c2d env maxJobDuration decreased and updated operator-service
4. Dataset metadata updated, timeout validity decreased

if user use c2d via market, and user refresh the page or change algorithm => change back previous algorithm, then initializeCompute will for sure return a **new validUntil** which guarantee > **previous validUntil**

**Comment by alexcos20** [comment]
or just fetch the previous valid providerFees from https://github.com/oceanprotocol/ocean-subgraph/issues/471 and take that validUntil from providerData

**Comment by soonhuat** [comment]
@calina-c haven't test this yet, but should be solved the latest subgraph, and a bit of market enhancement, will only able to test this by next
however, you could close this first
