### ISSUE TITLE
FileInfo Endpoint

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#504]
Right now, this endpoint supports only 2 scenarios:
 - did  - and provider will decode/decrypt whatever data source is used
 - url

2nd scenario (just url) breaks the current definition of url-storage (see https://docs.oceanprotocol.com/concepts/did-ddo/#files)
We should accept the full object, like:
```
[
    "type": "url",
    "url": "https://url.com/file1.csv",
    "method": "GET",
    "headers":
      [
       {"Authorization": "Bearer 123"}, 
       {"APIKEY": "124"},
]
```

**Comment by AnaLoznianu** [comment]
Breaking change for the market

**Comment by calina-c** [comment]
It's already like this.

![Screenshot 2022-06-28 at 07.28.17.png](https://images.zenhubusercontent.com/5795cf04e40e5714b16c76c5/127376e1-395f-48ad-8b96-76b5591ee6fa)

**Comment by alexcos20** [comment]
and how a POST is handled ?
for headers we already have #492

**Comment by calina-c** [comment]
There is a correction to do on fileinfo, where it does not use the POST method, but the original ticket description is not accurate. Fileinfo DOES accept a full url object, so this is not a breaking change for the market or other repos. I am making the correction for the POST case and adding headers in the same PR.

**Comment by calina-c** [comment]
There is a correction to do on fileinfo, where it does not use the POST method, but the original ticket description is not accurate. Fileinfo DOES accept a full url object, so this is not a breaking change for the market or other repos. I am making the correction for the POST case and adding headers in the same PR.
