### ISSUE TITLE
Provider 1.1.0 c2d start job fails if no checksum in container property

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/provider#509]
When trying to start a c2d with the provider checks for the checksum also.
 
400 Error response:
`{"error": "algorithm container must specify values for all of entrypoint, image and checksum."}`

Later edit: if the algorithm's container ddo property contains something on the checksum field the job will start, even if the random string is not related to the container itself.

Provider logs:
`2022-06-30 11:35:44 provider-77fcdf456-h9wrx ocean_provider.routes.compute[13] ERROR algorithm container must specify values for all of entrypoint, image and checksum.
  |   | 2022-06-30 11:35:44 provider-77fcdf456-h9wrx ocean_provider.utils.datatoken[13] DEBUG record_consume_request: did=did:op:5a0abdd6ff2b660e6be6f897aa2eae830fc0d95516a40bdd6b19ab3f41662f44, service_id=ac9265c24b006998750a7cf334e3fb68c84a19fdfd2676821458bc31dea7baaa, transfer_tx_id=0xdb7d3344168834ed6ee1dfdeced10b3f041de7d64f7cc0aec63117924aaa7e73, consumer_address=0x968d4670c346275edd5CC1A7535D14b631FFc49C, token_address=0x9ca8B3FE04072d6cE41625A13D545F1244801dab, amount=1
  |   | 2022-06-30 11:35:44 provider-77fcdf456-h9wrx ocean_provider.utils.datatoken[13] DEBUG validate_transfer_not_used_for_other_service: did=did:op:5a0abdd6ff2b660e6be6f897aa2eae830fc0d95516a40bdd6b19ab3f41662f44, service_id=ac9265c24b006998750a7cf334e3fb68c84a19fdfd2676821458bc31dea7baaa, transfer_tx_id=0xdb7d3344168834ed6ee1dfdeced10b3f041de7d64f7cc0aec63117924aaa7e73, consumer_address=0x968d4670c346275edd5CC1A7535D14b631FFc49C, token_address=0x9ca8B3FE04072d6cE41625A13D545F1244801dab
  |   | 2022-06-30 11:35:44 provider-77fcdf456-h9wrx ocean_provider.utils.datatoken[13] DEBUG validate_order succeeded for: did=did:op:5a0abdd6ff2b660e6be6f897aa2eae830fc0d95516a40bdd6b19ab3f41662f44, service_id=ac9265c24b006998750a7cf334e3fb68c84a19fdfd2676821458bc31dea7baaa, tx_id=0xdb7d3344168834ed6ee1dfdeced10b3f041de7d64f7cc0aec63117924aaa7e73, sender=0x968d4670c346275edd5CC1A7535D14b631FFc49C, num_tokens=1, token_address=0x9ca8B3FE04072d6cE41625A13D545F1244801dab. result is: tx=AttributeDict({'accessList': [], 'blockHash': HexBytes('0xbe54abf64cc96ca7c6e71b17ab1ddadc2cd6452607f1a9784723634c2877cb00'), 'blockNumber': 10942172, 'chainId': '0x4', 'from': '0x968d4670c346275edd5CC1A7535D14b631FFc49C', 'gas': 48474, 'gasPrice': 1100218223, 'hash': HexBytes('0xdb7d3344168834ed6ee1dfdeced10b3f041de7d64f7cc0aec63117924aaa7e73'), 'input': '0x361fef49ba658fa1574f2036e33f1db54446894d61c82a099202ec9c2c866f87200a1fdb000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000c6a0bc5cd0078d6cd0b659e8061b404cfa57040000000000000000000000008967bcf84170c91b0d24d4302c2376283b0b3a070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001cb787c96d021eb4c790e14f13a29cdd199b00dff202c64ef3f42bb1dd84688c3c28d4164c62e12ccab0543d5d1bd8652c011be0bb284720b5395d2ca5427b0bc30000000000000000000000000000000000000000000000000000000062bd8ac50000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000004a7b22656e7669726f6e6d656e74223a22636f6d707574652d76342d656e67696e652d6465762d656e7632222c2274696d657374616d70223a313635363538383837382e3534313433347d00000000000000000000000000000000000000000000', 'maxFeePerGas': 1100218223, 'maxPriorityFeePerGas': 1100218223, 'nonce': 1529, 'r': HexBytes('0x5bbcd7f541243f187cb99026904579aea8a80cd545295db41b5a2ddad52530db'), 's': HexBytes('0x2677275c80451c86cdd5a74fb5da3f7f0754afb58011c51b7d5aeb22122b4d99'), 'to': '0x9ca8B3FE04072d6cE41625A13D545F1244801dab', 'transactionIndex': 41, 'type': '0x2', 'v': 1, 'value': 0}), order_event=AttributeDict({'args': AttributeDict({'consumer': '0xCfA40cc2A2f6D3BAE0D6eFaf3e760b1Ec02e6dCf', 'publishMarketAddress': '0x9984b2453eC7D99a73A5B3a46Da81f197B753C8d', 'payer': '0x968d4670c346275edd5CC1A7535D14b631FFc49C', 'amount': 1000000000000000000, 'serviceIndex': 0, 'timestamp': 1656586984, 'blockNumber': 10942042}), 'event': 'OrderStarted', 'logIndex': 54, 'transactionIndex': 24, 'transactionHash': HexBytes('0xba658fa1574f2036e33f1db54446894d61c82a099202ec9c2c866f87200a1fdb'), 'address': '0x9ca8B3FE04072d6cE41625A13D545F1244801dab', 'blockHash': HexBytes('0xbc3cf34c2310514b4d6cfae02299cca944fef1dd99255c15b5473f2b36f6bdb5'), 'blockNumber': 10942042}).
  |   | 2022-06-30 11:35:44 provider-77fcdf456-h9wrx web3.providers.HTTPProvider[13] DEBUG Getting response HTTP. URI: https://rinkeby.infura.io/v3/e823d740755648669f3c9115d26c8fe3, Method: eth_getTransactionByHash, Response: {'jsonrpc': '2.0', 'id': 367, 'result': {'accessList': [], 'blockHash': '0xbe54abf64cc96ca7c6e71b17ab1ddadc2cd6452607f1a9784723634c2877cb00', 'blockNumber': '0xa6f6dc', 'chainId': '0x4', 'from': '0x968d4670c346275edd5cc1a7535d14b631ffc49c', 'gas': '0xbd5a', 'gasPrice': '0x4193ff6f', 'hash': '0xdb7d3344168834ed6ee1dfdeced10b3f041de7d64f7cc0aec63117924aaa7e73', 'input': '0x361fef49ba658fa1574f2036e33f1db54446894d61c82a099202ec9c2c866f87200a1fdb000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000c6a0bc5cd0078d6cd0b659e8061b404cfa57040000000000000000000000008967bcf84170c91b0d24d4302c2376283b0b3a070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001cb787c96d021eb4c790e14f13a29cdd199b00dff202c64ef3f42bb1dd84688c3c28d4164c62e12ccab0543d5d1bd8652c011be0bb284720b5395d2ca5427b0bc30000000000000000000000000000000000000000000000000000000062bd8ac50000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000004a7b22656e7669726f6e6d656e74223a22636f6d707574652d76342d656e67696e652d6465762d656e7632222c2274696d657374616d70223a313635363538383837382e3534313433347d00000000000000000000000000000000000000000000', 'maxFeePerGas': '0x4193ff6f', 'maxPriorityFeePerGas': '0x4193ff6f', 'nonce': '0x5f9', 'r': '0x5bbcd7f541243f187cb99026904579aea8a80cd545295db41b5a2ddad52530db', 's': '0x2677275c80451c86cdd5a74fb5da3f7f0754afb58011c51b7d5aeb22122b4d99', 'to': '0x9ca8b3fe04072d6ce41625a13d545f1244801dab', 'transactionIndex': '0x29', 'type': '0x2', 'v': '0x1', 'value': '0x0'}}
  |   | 2022-06-30 11:35:44 provider-77fcdf456-h9wrx urllib3.connectionpool[13] DEBUG https://rinkeby.infura.io:443 "POST /v3/e823d740755648669f3c9115d26c8fe3 HTTP/1.1" 200 713`

**Comment by alexcos20** [comment]
Provider 1.1.0 needs  container.checksum field to be defined and non empty.
Once https://github.com/oceanprotocol/operator-engine/pull/70 is merged & deploy, we will use checksum field to start the job

**Comment by calina-c** [comment]
Yes, this is an intentional change. Should we close this ticket?

**Comment by calina-c** [comment]
@bogdanfazakas I'm just writing this as an update, I know you already know :D there is a provider image called `container-checksums-check` which contains enforces rules for container checksum structure (start with "sha256:") and also checks dockerhub that the image is valid. This is now part of the algorithm validation, so it will work for initializeCompute and computeStart.

**Comment by mihaisc** [comment]
@bogdanfazakas is this still an issue? or we close this
