### ISSUE TITLE
Provider:  add sample deploy files

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#51]
Create a folder deployment
 - add sample files of how to run the provider as a systemd service
 - add sample files of how to run the provider using docker-compose
 - add sample files of how to run the provider in a k8 enviroment (yaml file)

**Comment by md00ux** [comment]
[Provider](https://github.com/oceanprotocol/provider) has the following dependencies:
- [Aquarius](https://github.com/oceanprotocol/aquarius) 
- Ethereum network

which means these components must be available before the deployment.

The following template could be customized based on environment's specifics:
[provider-deploy.txt](https://github.com/oceanprotocol/provider/files/5984598/provider-deploy.txt)
(rename .txt to .yaml before deployment)

Tip: before deployment you can [validate](https://github.com/instrumenta/kubeval) the yaml file.

```
kubectl config set-context --current --namespace ocean
kubectl apply -f provider-deploy.yaml
deployment.apps/provider created

kubectl get pod -l app=provider
NAME                        READY   STATUS    RESTARTS   AGE
provider-764ffbdb59-bgmnl   1/1     Running   0          55s
```
