### ISSUE TITLE
Double check that rpc urls are removed from logs and error_messages

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#521]
Message from Discord:
Still seeing 429 messages when I try to download an asset. {"error":"=Order with tx_id 0x6ac45dc73d09c015b3145d747448db1693531e6e2bfe78e325461b420b1dcb10 could not be validated due to error: 
429 Client Error: Too Many Requests for url: URL stripped for security reasons} 
URL: https://v4.provider.rinkeby.oceanprotocol.com/api/services/download?fileIndex=0&documentId=did:op:da266ac10885d634d65caa36a23e6c5c6d54a1caf3fa41f3430bae31164f899d&transferTxId=0x6ac45dc73d09c015b3145d747448db1693531e6e2bfe78e325461b420b1dcb10&serviceId=0&consumerAddress=0x790E7D119765e6c9B6765cCd83B5F20ddECf536f&nonce=1659983768435&signature=0x35528534c9ba435e382f1ffd70848d70949b3f82d2f814138eac7aa681a9af7d50e0484aaa964606dfd994ffd86023f4d5d730771b5cff5008e68e51994115651c

Double check if our infura keys are leaked.

**Comment by calina-c** [comment]
I checked. Provider does not seem to expose the RPC url.
