### ISSUE TITLE
Random error on ordering

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#522]
error : https://gist.github.com/mihaisc/ca64fc8e6a230bed1b3dd4c4b4471104

**Comment by AnaLoznianu** [comment]
I encountered the provider error on this asset: https://market.oceanprotocol.com/asset/did:op:bd81f459ff83ceeb06c917aa7a6e42c3d2e42ad805ad2ce028ed40bb39b46213

<img width="1280" alt="Screenshot 2022-08-09 at 18 50 38" src="https://user-images.githubusercontent.com/84312885/183699305-abfb5c61-e904-4a6e-82a6-8aab1a672130.png">

**Comment by mihaisc** [comment]
when reporting please also provide a approximate  timestamp

**Comment by mihaisc** [comment]
The issue Ana encountered is not related . It is because they are using the basic template, not the enterprise one.

**Comment by corrie-sloot** [comment]
I feel like this could be a common mistake. Can we make it so provider checks if it is the wrong template, and returns an error message?

**Comment by AnaLoznianu** [comment]
@corrie-sloot Sounds interesting. @calina-c Is it technically possible to do it?

**Comment by mihaisc** [comment]
No, this is not a provider issue and all the discussions here have nothing to do with the initial error. The problem described can't be handled in provider. In the market we are using a contract call that works on one template but not the other . So the call is made and is successful but because of internal checks it doesn't/can't do the actual order.  So no order existing means provider can't do anything. It will be handled in the market

**Comment by calina-c** [comment]
@AnaLoznianu @mihaisc so are we repurposing this issue for the "different template" case? Then, can I get those reproduction steps?

**Comment by AnaLoznianu** [comment]
No @calina-c. I created a separate market issue for that problem. I'll remove all the details to that one so no one gets confused

**Comment by mihaisc** [comment]
I'll close this and open another when i have time to debug the initial issue.
