### ISSUE TITLE
Key => Error validations in Provider

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/provider#529]
Provider validation error codes are now strings. To improve readability, we can transform that into key => value pairs, where the key is the field where the error originated, and the value is the error itself as a string.

I support key => value errors descriptions, it makes it more readable by devs

_Originally posted by @alexcos20 in https://github.com/oceanprotocol/provider/issues/525#issuecomment-1219349929_

**Comment by AnaLoznianu** [comment]
Closed by: https://github.com/oceanprotocol/provider/pull/525
