### ISSUE TITLE
Provider: ocean.py marketplace quickstart hangs when downloading >1 files

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/provider#54]
When I was working to solve "ocean.py marketplace quickstart fails" [ocean.py #89](https://github.com/oceanprotocol/ocean.py/issues/89), I encountered an issue: it would hang when trying to download >1 files.

My priority was to get the flow working. So I switched from needing 3 services to 1, and from using AWS to using github and a file that I knew to be small. That resolved my immediate priority.

While I still had it set up for 3 services, I traced the code. It seemed to be hanging inside the requests.py library, when doing chunked iterations towards downloading. It hung for >10 min. Was this a large file issue? No - Samer and Alex tell me that the file was small. 

Alex also mentioned that he has success using >1 service in compute-to-data settings.

Today in standup someone else mentioned this being a possible issue in provider.py. 

To reproduce this bug on a codebase as close-as-possible to the current codebase:
1. Branch from current ocean.py 
2. In marketplace quickstart, copy in the metadata/services info from code prior to the commit that solves ocean.py `#89` . [This commit has the relevant changes](https://github.com/oceanprotocol/ocean.py/commit/3c5e07f02ecca817c50231a93fdea2bc39fdd75d) which allowed to run to the end of step 7/7.
3. Run marketplace quickstart. There may be two outcomes: (a) it fails like I had above. (b) It doesn't fail due to other bug fixes since this issue was reported. 

TODOs for this issue:
- [x] try to reproduce, as given above. It may or may not fail, see step 3 above.
- [x] write a unit or system test on >1 file. It may or may not fail, as mentioned
- [ ] if there was an issue: fix the issue 
- [ ] as part of PR, re-deploy to pip following the deploy process [ocean.py#188](https://github.com/oceanprotocol/ocean.py/issues/118), [provider#78](https://github.com/oceanprotocol/provider/issues/78)

**Comment by calina-c** [comment]
@mariacarmina ocean_lib version 0.5.18 was released, so you should be able to test this
