### ISSUE TITLE
Initialize fails for larger files hosted on google drive 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#546]
Asset: https://market.oceanprotocol.com/asset/did:op:41c67fcc41bf0e04de8b5f08fef515fa53165e2a01429b779fc9f59da6cf501e
Logs
```
2022-10-18 14:56:04 | NoneType: None
 2022-10-18 14:56:04 | 2022-10-18 11:56:04 provider-679b7d8bd5-h2gwr ocean_provider.routes.consume[12] 
ERROR Error: Asset URL not found or not available. Payload was: ImmutableMultiDict([('documentId', 
'did:op:41c67fcc41bf0e04de8b5f08fef515fa53165e2a01429b779fc9f59da6cf501e'), 
('serviceId', '69c8869dd4c5b773933251f82e42af3216e0d0d3961bf84bd7bb8a7f490a20cd'), ('fileIndex', '0'), 
('consumerAddress', '0x8eAC3cF74fe6dC46A8ed9bF07a15F67dFbeEFdc9')])
```
Gdrive link: https://drive.google.com/uc?export=download&id=1xJUtMfJzF8KPShSC9ZZ2frAQ6m0NWfDv&confirm=9iBg

**Comment by AnaLoznianu** [comment]
Docs related issue: https://github.com/oceanprotocol/docs/issues/1144

**Comment by AnaLoznianu** [comment]
After a lot of investigation, we reached the conclusion this is a GDrive issue. Even in the browser, the file sometimes is downloaded, and other times it is not. 
We cannot fix it from our side. 
We will recommend people use a proper storage solution like azure or AWS. We will also display a warning message in the [market](https://github.com/oceanprotocol/market/issues/1750) when people are using drive links.

**Comment by AnaLoznianu** [comment]
Great suggestion, I've updated the docs task here: https://github.com/oceanprotocol/docs/issues/1144
cc @mariacarmina
