### ISSUE TITLE
Document provider errors 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/provider#548]
- [ ] create a README or a file to document the errors and the status codes that the provider returns
- [ ] add a link in the docs https://github.com/oceanprotocol/docs/issues/1143
- [ ] Provider related issue: https://github.com/oceanprotocol/provider/issues/523

**Comment by trentmc** [comment]
Blocked by C2D environments issue (provider#606)

**Comment by mariacarmina** [comment]
further work to do:

- [ ] add fileinfo errors
- [ ] add initialize errors
