### ISSUE TITLE
Provider: Auth tokens

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#55]
Provider can generate an access token for a consumer , for a specified asset, for a specific expiry time if the user can provide the txid of the ownership (very similar with the download endpoint, but instead of download, it will generate the access_token)

You cannot request more that 1 access_tokens for the same txId with multiple consumers  (it's fine to request multiple access_tokens for the same txId and the same consumer)

Provider will keep the token into a database, along with used=0  , expiry = timestamp of expiration date, did, address, etc

At usage, used is incremented, so that auth token cannot be used anymore

Access token = did + consumer , signed by the provider with the provider's private key

On consume, Provider will request access token  (message) + signature  of that message signed by the consumer and compare it with the database

For compute 2 data , the consumer will request access token for each dataset (algo, etc) , it's going to sign the requests using the auth tokens and provider will generate access urls that are going to be passed from the provider to operator - service , all the way till pod-configure

This access_token can be used for download endpoint instead of nonce

**Comment by ssallam** [comment]
this feature has been shelved.
