### ISSUE TITLE
No `ARWEAVE_GATEWAY` defined error when using Arweave as provider type

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/provider#555]
**Describe the bug**  ``
When trying to call `getFileInfo` with Arweave we get the following error:
`No ARWEAVE_GATEWAY defined, can not resolve arweave transaction id.`

Network response:
<img width="723" alt="Screenshot 2022-10-27 at 08 07 43" src="https://user-images.githubusercontent.com/13741335/198280788-949bc61a-cc0d-4dd4-87c6-cdf9bf58142f.png">

endpoint: https://v4.provider.mumbai.oceanprotocol.com/api/services/fileinfo

payload: 
`{
    "type": "arweave",
    "transactionId": "qDGiE4q1N3m5w_zkr4Np1OLW4iS9A79j3GcyVomp0ZM"
}`

response:
`{
    "context": {
        "transactionId": "qDGiE4q1N3m5w_zkr4Np1OLW4iS9A79j3GcyVomp0ZM",
        "type": "arweave",
        "userdata": null
    },
    "error": "No ARWEAVE_GATEWAY defined, can not resolve arweave transaction id."
}`

**Comment by calina-c** [comment]
I asked Marian to define ARWEAVE_GATEWAY=https://arweave.net/ and it's done in Mumbai. @EnzoVezzaro can you please check if it works now? If so, we need to update this variable for all networks.

**Comment by md00ux** [comment]
Added `ARWEAVE_GATEWAY=https://arweave.net/` for Mumbai Provider

**Comment by EnzoVezzaro** [comment]
> Added `ARWEAVE_GATEWAY=https://arweave.net/` on all Provider deployments.

on my end it's all working as expected 👍🏽 thank you guys @calina-c @md00ux

**Comment by alexcos20** [comment]
default gateway added in provider 1.3.7, so we can close this
