### ISSUE TITLE
`fileInfo` IPFS validation not working as expected

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/provider#558]
**Describe the bug**
When validating any IPFS cid, I always get `valid: false` even though the file is a valid one. 

Endpoint: https://v4.provider.mumbai.oceanprotocol.com/api/services/fileinfo

Payload:
`{
    "type": "ipfs",
    "hash": "bafkreiaxfszya2qz3vdgdw3da3rbfsvnlwez2x5wjaf66uqheeo22nc3fu"
}`

Result:
`{
    "index": 0,
    "valid": false
}`

This dataset is valid, you can view it with the following link: https://nftstorage.link/ipfs/bafkreiaxfszya2qz3vdgdw3da3rbfsvnlwez2x5wjaf66uqheeo22nc3fu

**Comment by alexcos20** [comment]
since our provider is connected to a non existent ipfs service, of course it will not work :)

I will take it from here

**Comment by alexcos20** [comment]
![Clean Ubuntu 64-bit - VMware Workstation 16 Player (Non-commercial use only) 11_6_2022 1_36_14 PM](https://user-images.githubusercontent.com/7489447/200168279-67de3bb0-a135-418d-90c0-982509ef073d.png)

all good now.

@AnaLoznianu @EnzoVezzaro ^
