### ISSUE TITLE
initialize provider fails with `IPFS` file

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/provider#561]
**Describe the bug** 
Provider fails when initializing on [asset](https://market.oceanprotocol.com/asset/did:op:d2f0d92d6fc7fe0f3a44db1cb653ab27a040068bfbe13a94ef5d535cc2ebabcc) which uses an IPFS file. 

**To Reproduce**

Endpoint:
`https://v4.provider.mumbai.oceanprotocol.com/api/services/initialize?documentId=did:op:d2f0d92d6fc7fe0f3a44db1cb653ab27a040068bfbe13a94ef5d535cc2ebabcc&serviceId=ecbb9d2ad9b6fbe8d593d6f1d9856a85cfe8a8c5f70426894f7307e59f7054d2&fileIndex=0&consumerAddress=0x0000000000000000000000000000000000000000`

Payload:
`{
documentId: did:op:d2f0d92d6fc7fe0f3a44db1cb653ab27a040068bfbe13a94ef5d535cc2ebabcc,
serviceId: ecbb9d2ad9b6fbe8d593d6f1d9856a85cfe8a8c5f70426894f7307e59f7054d2,
fileIndex: 0,
consumerAddress: 0x0000000000000000000000000000000000000000
}`

Result:
`{
    "error": "Error: Asset URL not found or not available. Payload was: ImmutableMultiDict([('documentId', 'did:op:d2f0d92d6fc7fe0f3a44db1cb653ab27a040068bfbe13a94ef5d535cc2ebabcc'), ('serviceId', 'ecbb9d2ad9b6fbe8d593d6f1d9856a85cfe8a8c5f70426894f7307e59f7054d2'), ('fileIndex', '0'), ('consumerAddress', '0x0000000000000000000000000000000000000000')])"
}`

**Comment by alexcos20** [comment]
@EnzoVezzaro - see slack
