### ISSUE TITLE
FileInfo endpoint can lead to DDOS

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#562]
if checksum is required, limit the file size, because this can lead to major outages and DDOS attacks
We only need checksum for algos, so we can do checksums only for small files.

Proposal:
- define a limit (env var)
- make sure that the limit is obeyed
- if file is larger, do not compute checksum

**Comment by AnaLoznianu** [comment]
Let's limit the algorithm size to 20 MB and add this information inside the docs as well.
