### ISSUE TITLE
Test Multichain Provider

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/provider#591]
from @alexcos20 let's test this:

- [x] create docker image  -     image "oceanprotocol/provider-py:multichain" available
- [x] @md00ux - create CNAMEs https://v4-2.provider.NETWORK.oceanprotocol.com that points to https://v4.provider.NETWORK.oceanprotocol.com/  (for the NETWORKs: mumbai, goerli, polygon)
- [x] create market PR that uses new CNAMES for provider URI
- [x] publish assets (datasets & algorithms), using all known storage types:  url, graphql, ipfs, smartcontract, etc
- [x] make sure consumption works for all previous created assets
- [x] @md00ux - deploy multichain provider to https://v4.provider.oceanprotocol.com, using private keys from existing providers (this can be done anytime, there is no deps or blocker)
- [x] once previous steps are done, @md00ux changes all v4-2 CNAMES to point towards multichain provider (IE: https://v4-2.provider.mainnet.oceanprotocol.com/  points to https://v4.provider.oceanprotocol.com
- [x] make sure consumption works for all previous created assets
- [x] update market PR to use https://v4.provider.oceanprotocol.com as provider URI for all networks
- [x] publish another set of assets (datasets & algorithms), using all known storage types:  url, graphql, ipfs, smartcontract, etc
- [x] make sure consumption works for all previous created assets

**Comment by calina-c** [comment]
@AnaLoznianu can we consider this closed? The new multichain provider is released and integrated into Barge, as well as the new Aquarius version that accurately "communicates" with the new provider. The deployed multichain provider endpoints are active and have been tested, as far as I know. Should we still keep this ticket?
