### ISSUE TITLE
Known issue: compute environments disappear in CI

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/provider#606]
When running the CI, the list of c2d environments disappears for no apparent reason. This affects provider and ocean.py CIs, effectively blocking further development.

We thought it was temporarily fixed by waiting through a retry mechanism here: https://github.com/oceanprotocol/provider/pull/603 but it seems that fix is not enough.

**Comment by mariacarmina** [comment]
UPDATE:

Checked the connection in this PR on provider https://github.com/oceanprotocol/provider/pull/610/files where I modified the workflow and an old URL and it seems that always the connection is successful https://github.com/oceanprotocol/provider/actions/runs/4345076005/jobs/7589748740#step:8:1, but when provider try to connect to `http://172.15.0.13:31000`, it occurs Connection refused.

**Comment by mariacarmina** [comment]
Approaches for debug shown [here](https://github.com/oceanprotocol/provider/pull/610#issuecomment-1467211549)
