### ISSUE TITLE
fileinfo endpoint should only allow GET method

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/provider#621]
**Describe the bug**
fileinfo endpoint suppose to do a health/ping should restrict http method based on file type or only GET method:
GraphQL: POST or GET
everything other type: GET

**To Reproduce**
1. Send request to fileinfo with curl or postman of type URL
2. With body { method: POST }

**Expected behavior**
Request of the not allowed method (DELETE, PUT, maybe also POST) should be rejected

**Additional context**
When download request initiated, if the request is going to be GET, so should fileinfo endpoint.

**Comment by mihaisc** [comment]
The problem is mainly when provider is used as proxy and the urls are internal. By allowing all the methods we may allow various vectors of attacks

**Comment by alexcos20** [comment]
I lean towards allowing only GET and POST.  I see no reason to use DELETE and PUT

**Comment by soonhuat** [comment]
PR: https://github.com/oceanprotocol/provider/pull/623

**Comment by calina-c** [comment]
> I lean towards allowing only GET and POST. I see no reason to use DELETE and PUT

That is already the case. @soonhuat is suggesting removing POST as well

**Comment by calina-c** [comment]
Closed as intended functionality, alonside its PR.
