### ISSUE TITLE
Cannot retrieve results from compute to data job

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/provider#642]
**Describe the bug**
Cannot retrieve results from compute to data job & it's stuck in certain phases (e.g. `Warming Up`, `Running algorithm`)

**To Reproduce**
1. Publish an algorithm through Ocean Market / ocean.py using barge network
2. Check compute jobs tab
3. See error

**Expected behavior**
To be able to retrieve the results and have C2D job completed.

**Screenshots**
![image](https://github.com/oceanprotocol/provider/assets/50501033/6c0b97c2-8a8b-45ea-8533-79881fb859fa)

**Additional context**
It is reported also in a [Discord thread](https://discord.com/channels/612953348487905282/1103192968778764310).
For ocean.py [this ](https://github.com/oceanprotocol/ocean.py/actions/runs/4959427626/jobs/8873515837?pr=1427#step:9:313)is the run where C2D get stuck.

**Comment by Babitabisht** [comment]
In my case it was earlier getting stuck on 'Data provisioning failed', after modifying this line
 export POD_CONFIGURATION_VERSION=${POD_CONFIGURATION_VERSION:-oceanprotocol/pod-configuration:v4main} to
export POD_CONFIGURATION_VERSION=${POD_CONFIGURATION_VERSION:-oceanprotocol/pod-configuration:new_timeouts}  (in start_ocean.sh)  the status got changed to 'Running algorithm'. 

I am on Ubuntu 20.04 VM. Running the market from the branch 'fix/issue-fix-barge-connection'.

**Comment by mariacarmina** [comment]
It is fixed now if you update barge. Closing this.
