### ISSUE TITLE
Add network-name in each of the provider logs

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/provider#644]
As we now have the multichain provider, reading the logs is a bit difficult. 
I'd love to have a way to filter the logs for a specific network. To do this, we need to log the network name with each of the provider logs

**Comment by AnaLoznianu** [comment]
@mariacarmina @alexcos20 I am wondering if this is already done or not

**Comment by mihaisc** [comment]
valid, if effort is low enough let's upgrade the current provider. Will include this in nodes indexer as well
