### ISSUE TITLE
release process & deployment is undocumented

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/provider#78]
How to do a tagged release with a GitHub release? How do builds end up in use for `market`? Where do builds happen? How is the CHANGELOG.md updated, cause it's empty right now? What are the deployment URLs?

Examples of structure:
- for ocean.js - https://github.com/oceanprotocol/ocean.js#-production
- for ocean.py - https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/release-process.md (but ideally shorter, see [ocean.py#179](https://github.com/oceanprotocol/ocean.py/issues/179))

**Comment by trentmc** [comment]
High priority because not having it is big friction for anyone fixing bugs or enhancing ocean.py.

**Comment by calina-c** [comment]
@akshay-ap any updates on this? It was started 7 months ago and last updated 2 months ago.

**Comment by trentmc** [comment]
afaik Akshay has not been working on this at all. If you want to take it over, go for it.

**Comment by calina-c** [comment]
Closed by #206.
